development:
  database: softtek_dev
  adapter: postgresql
  host: localhost

test:
  database: softtek_test
  adapter: postgresql
  host: localhost

stage:
  adapter: postgresql
  database: softtek_stage
  pool: 5
  timeout: 5000

production:
  database: softtek_production
  adapter:  postgresql
  host:     127.0.0.1
  username: deploy
  password: deploy
  pool:     20
  timeout:  30000
